services:
  # ---  DATABASE ---
  postgres-db:
    image: postgres:16-alpine
    container_name: sports-booking-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
    networks:
      - my-network

  # ---  BACKEND ---
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: sports-booking-backend
    ports:
      - "${SERVER_PORT}:3000"
      - "${PRISMA_STUDIO_PORT}:5555"
    volumes:
      # Mount folder backend để hot-reload
      - ./apps/backend:/app
      - /app/node_modules
    env_file:
      - ./apps/backend/.env
    depends_on:
      - postgres-db
    restart: always
    networks:
      - my-network

  # ---  FRONTEND ---
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: sports-booking-frontend
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      # Mount folder frontend để hot-reload
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - ./apps/frontend/.env
    restart: always
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
