FROM node:22-alpine

WORKDIR /app

# Chỉ copy package.json của frontend
COPY package*.json ./

# Cài đặt dependencies cho riêng frontend
RUN npm install

# Copy toàn bộ code frontend
COPY . .

# Expose port mặc định của Vite
EXPOSE 5173

# Chạy trực tiếp không cần --workspace
CMD ["npm", "run", "dev", "--", "--host"]
