FROM node:22-alpine

# Cài đặt các thư viện cần thiết cho Prisma (openssl)
RUN apk add --no-cache openssl

WORKDIR /app

# Chỉ copy package.json của backend
COPY package*.json ./

# Cài đặt dependencies cho riêng backend
RUN npm install

# Copy toàn bộ code backend
COPY . .

# Generate Prisma Client (sẽ tạo vào node_modules/.prisma/client)
RUN npx prisma generate

EXPOSE 3000

# Chạy trực tiếp không cần --workspace
CMD ["npm", "run", "dev"]
